package:
  name: pydeme
  version: 2.1.2

source:
  path: ..

build:
  script_env:
    - CMAKE_CUDA_COMPILER=$BUILD_PREFIX/bin/nvcc
    - CUDA_HOME=$PREFIX
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }} # [not osx]
    - make
    - cmake
    - ninja

  host:
    - python
    - pip
    - pybind11
    - numpy
    - cuda-version=={{ cuda_compiler_version }} # [not osx]
    - cuda-runtime  # [not osx]
    - cuda-nvrtc-dev # [not osx]
    - cuda-cudart-dev # [not osx]
    - libcurand-dev # [not osx]

  run:
    - python
    - pybind11
    - numpy
    - cuda-version=={{ cuda_compiler_version }} # [not osx]
    - cuda-runtime  # [not osx]
    - cuda-cudart-dev # [not osx]
    - libcurand-dev # [not osx]

about:
  summary: PyDEME is a Python-wrapped library that provides easy accessibility to DEM Engine (A novel physics solver).
  home: https://github.com/projectchrono/DEM-Engine
  license: BSD 3-Clause